sh5wr5hx
2015-10-06 22:09:23.9897|INFO|thread: 1|ReactiveScreen|Activating
GitHub.ViewModels.AboutViewModel.
2015-10-06 22:09:04.3641|INFO|thread: 1|CommandLineHandler|Parsing
command line
arguments:C:\Users\GAD\Documents\GitHub\-Place-script\.git\hooks\README.sample
2015-10-06 22:09:04.3791|INFO|thread: 1|AppInstanceCommunicator|An
instance of GitHub Desktop is already running. Checking to see if we
should pass control...
2015-10-06 22:09:04.3791|INFO|thread: 1|AppInstanceCommunicator|Not a
call to clone a repo, so just run the app as usual.
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging|
#########################################
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| GitHub Desktop
started. VERSION: 3.0.5.2
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| Build version:
a0622a5279b4491e0f43dbed6bd0709d1b40123e
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging|
***************************************
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***
***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***
***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***        Have
a problem?          ***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***    Email
support@github.com     ***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***      and
include this file      ***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***
***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ***
***
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging|
***************************************
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| OS Version:
Windows NT 6.3.9600.0 amd64
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| CLR Version:
4.0.30319.34011
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| Current culture:
ru-RU
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| Terminal
Services session: no
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| Location:
C:\Users\GAD\AppData\Local\Apps\2.0\Y1762BWD.M30\QYMZC3E1.2BQ\gith..tion_317444273a93ac29_0003.0000_30c6a4a3ecafb094\GitHub.exe
2015-10-06 22:09:04.3791|INFO|thread: 4|StartupLogging| ActivationUri:
https://github-windows.s3.amazonaws.com/GitHub.application
2015-10-06 22:09:04.4071|INFO|thread: 4|GitEnvironment|Process set up
with this SSH Agent info: 3648:/tmp/ssh-A1tKCBguHPpd/agent.3580
2015-10-06 22:09:04.4071|INFO|thread: 4|GitEnvironment|PATH is
C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd;C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin;C:\Users\GAD\AppData\Local\Apps\2.0\Y1762BWD.M30\QYMZC3E1.2BQ\gith..tion_317444273a93ac29_0003.0000_30c6a4a3ecafb094;C:\Users\GAD\AppData\Local\GitHub\lfs-amd64_0.5.4;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\ProgramData\Oracle\Java\javapath;C:\Program
Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
Client\;C:\Program Files (x86)\NVIDIA
Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program
Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\IPT
2015-10-06 22:09:04.4071|INFO|thread: 4|StartupLogging|
=====================================================
2015-10-06 22:09:04.4071|INFO|thread: 4|StartupLogging|  DIAGNOSTICS
|
2015-10-06 22:09:04.4071|INFO|thread: 4|StartupLogging|
=====================================================
2015-10-06 22:09:04.4071|INFO|thread: 4|StartupLogging| Git Extracted:
'True:
2015-10-06 22:09:04.4071|INFO|thread: 4|StartupLogging| PortableGit Dir
Exists:
'C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad'
2015-10-06 22:09:04.4071|INFO|thread: 1|HardwareRenderingHelper|Your
video card appears to support hardware rendering. If this isn't the case
and you see glitches
2015-10-06 22:09:04.4071|INFO|thread: 1|HardwareRenderingHelper|set the
GH_FORCE_SW_RENDERING environment variable to 1
2015-10-06 22:09:04.4071|INFO|thread: 4|StartupLogging| Git Executable
Exists:
'C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\git.exe'
2015-10-06 22:09:04.4071|INFO|thread: 1|App|Checking whether application
is network deployed.
2015-10-06 22:09:04.4111|INFO|thread: 4|StartupLogging|
----------------------------------------------------
2015-10-06 22:09:04.4111|INFO|thread: 4|StartupLogging| PATH:
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files
(x86)\NVIDIA
Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program
Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
(x86)\Intel\Intel(R) Management Engine Components\IPT
2015-10-06 22:09:04.4111|INFO|thread: 4|StartupLogger|Proxy information:
(None)
2015-10-06 22:09:04.4111|INFO|thread: 4|StartupLogger|Couldn't fetch
creds for proxy
2015-10-06 22:09:04.4612|INFO|thread: 1|ClickOnceAppIconHelper|Updating
registry with our application icon
'C:\Users\GAD\AppData\Local\Apps\2.0\Y1762BWD.M30\QYMZC3E1.2BQ\gith..tion_317444273a93ac29_0003.0000_30c6a4a3ecafb094\Images\App.ico'
2015-10-06 22:09:04.8514|INFO|thread: 4|PortablePackageManager|Already
extracted PortableGit.7z, returning 100%
2015-10-06 22:09:04.8975|INFO|thread:
4|MsysGitCertificateInstaller|Found certificate cache, loaded 162
certificates
2015-10-06 22:09:04.9175|INFO|thread:
4|MsysGitCertificateInstaller|Created certificate bundle with 161
entries
2015-10-06 22:09:04.9415|INFO|thread: 4|StartupSequence|Took 99ms to
Update certificate bundle from system store
2015-10-06 22:09:05.4879|INFO|thread:
1|CommandLineToolsExtractor|Portable Git and Git LFS are already
extracted
2015-10-06 22:09:05.4899|INFO|thread: 1|GitClient|Installing git lfs
filters
2015-10-06 22:09:05.4899|INFO|thread: 1|GitEnvironment|Process set up
with this SSH Agent info: 3648:/tmp/ssh-A1tKCBguHPpd/agent.3580
2015-10-06 22:09:05.4899|INFO|thread: 1|GitEnvironment|PATH is
C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd;C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin;C:\Users\GAD\AppData\Local\Apps\2.0\Y1762BWD.M30\QYMZC3E1.2BQ\gith..tion_317444273a93ac29_0003.0000_30c6a4a3ecafb094;C:\Users\GAD\AppData\Local\GitHub\lfs-amd64_0.5.4;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\System32
2015-10-06 22:09:05.4899|INFO|thread: 1|ProcessWrapper|Starting: Process
- FileName:
'C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\git.exe',
Args: 'lfs init --force ', Working Directory:
C:\Users\GAD\AppData\Local\Temp\
2015-10-06 22:09:05.4899|INFO|thread: 1|ReactiveScreen|Activating
GitHub.ViewModels.ShellViewModel.
2015-10-06 22:09:05.4899|INFO|thread: 1|ReactiveScreen|Activating
GitHub.ViewModels.DashboardViewModel.
2015-10-06 22:09:06.0023|INFO|thread: 1|PortablePackageManager|Already
extracted gitignore.7z, returning 100%
2015-10-06 22:09:06.3155|WARN|thread:13|LoginCache|Could not get login
for host 'GitHub.HostAddress'
System.Collections.Generic.KeyNotFoundException: The given key
'login:null' was not present in the cache.
2015-10-06 22:09:06.3335|INFO|thread:12|DashboardViewModel|Selected
repository ''
2015-10-06 22:09:06.3575|INFO|thread:12|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 1:GitClient.cs:663
2015-10-06 22:09:06.3575|INFO|thread: 4|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 1:GitClient.cs:663 after waiting
0.0013633s
2015-10-06 22:09:06.3575|INFO|thread:12|AsyncReaderWriterLock|Acquiring
exclusive scheduler for operation: 2:GitClient.cs:641
2015-10-06 22:09:06.4056|INFO|thread:13|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 1:GitClient.cs:663 after blocking
0.0469699s
2015-10-06 22:09:06.4056|INFO|thread: 4|AsyncReaderWriterLock|Acquired
exclusive scheduler for operation: 2:GitClient.cs:641 after waiting
0.0446774s
2015-10-06 22:09:06.8999|INFO|thread: 4|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 3:GitClient.cs:658
2015-10-06 22:09:06.9760|INFO|thread: 4|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 4:GitClient.cs:222
2015-10-06 22:09:06.9760|INFO|thread: 4|DashboardViewModel|Took 627ms to
Create RepositoryViewModel for location
C:\Users\GAD\Documents\GitHub\-Place-script
2015-10-06 22:09:06.9760|INFO|thread: 4|AsyncReaderWriterLock|Released
exclusive scheduler for operation: 2:GitClient.cs:641 after blocking
0.5705177s
2015-10-06 22:09:06.9760|INFO|thread:21|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 4:GitClient.cs:222 after waiting
0.0028393s
2015-10-06 22:09:06.9760|INFO|thread: 4|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 3:GitClient.cs:658 after waiting
0.0786938s
2015-10-06 22:09:06.9760|INFO|thread:21|GitClient|Loading commits for
repo: C:\Users\GAD\Documents\GitHub\-Place-script
2015-10-06
22:09:06.9910|INFO|thread:21|ConcurrentRepositoryConnection|No
references found for repo: C:\Users\GAD\Documents\GitHub\-Place-script\
2015-10-06 22:09:06.9910|INFO|thread:21|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 4:GitClient.cs:222 after blocking
0.0159882s
2015-10-06 22:09:07.0060|INFO|thread: 4|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 5:RepositoryViewModel.cs:325
2015-10-06 22:09:07.0060|INFO|thread: 5|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 5:RepositoryViewModel.cs:325 after
waiting 0.0010782s
2015-10-06 22:09:07.0060|INFO|thread: 4|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 3:GitClient.cs:658 after blocking
0.0295579s
2015-10-06 22:09:07.0420|WARN|thread:13|GetBranch`1|Could not resolve
branch origin/master
2015-10-06 22:09:07.0590|INFO|thread:13|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 5:RepositoryViewModel.cs:325 after
blocking 0.0511444s
2015-10-06 22:09:07.1471|INFO|thread: 1|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 6:GitClient.cs:199
2015-10-06 22:09:07.1471|INFO|thread: 7|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 6:GitClient.cs:199 after waiting
6.12E-05s
2015-10-06 22:09:07.1471|INFO|thread: 1|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 7:RepositoryModel.cs:596
2015-10-06 22:09:07.1471|INFO|thread: 5|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 7:RepositoryModel.cs:596 after
waiting 6.15E-05s
2015-10-06 22:09:07.1471|INFO|thread:13|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 8:RepositoryModel.cs:596
2015-10-06 22:09:07.1471|INFO|thread: 4|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 6:GitClient.cs:199 after blocking
0.0100204s
2015-10-06 22:09:07.1471|INFO|thread: 7|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 8:RepositoryModel.cs:596 after
waiting 0.0048732s
2015-10-06 22:09:07.1671|INFO|thread: 4|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 9:GitClient.cs:288
2015-10-06 22:09:07.1671|INFO|thread:13|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 9:GitClient.cs:288 after waiting
0.0031067s
2015-10-06 22:09:07.1671|INFO|thread:21|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 7:RepositoryModel.cs:596 after
blocking 0.0262404s
2015-10-06 22:09:07.1671|INFO|thread: 4|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 8:RepositoryModel.cs:596 after
blocking 0.0176087s
2015-10-06 22:09:07.1821|INFO|thread: 7|GitEnvironment|Process set up
with this SSH Agent info: 3648:/tmp/ssh-A1tKCBguHPpd/agent.3580
2015-10-06 22:09:07.1821|INFO|thread: 7|GitEnvironment|PATH is
C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd;C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin;C:\Users\GAD\AppData\Local\Apps\2.0\Y1762BWD.M30\QYMZC3E1.2BQ\gith..tion_317444273a93ac29_0003.0000_30c6a4a3ecafb094;C:\Users\GAD\AppData\Local\GitHub\lfs-amd64_0.5.4;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\System32
2015-10-06 22:09:07.1821|INFO|thread: 7|ProcessWrapper|Starting: Process
- FileName:
'C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\git.exe',
Args: 'status --untracked-files=all --porcelain -z ', Working Directory:
C:\Users\GAD\Documents\GitHub\-Place-script\
2015-10-06
22:09:07.2001|INFO|thread:21|ConcurrentRepositoryConnection|Took 13ms to
git status
2015-10-06
22:09:07.2001|INFO|thread:21|ConcurrentRepositoryConnection|Took 14ms to
git status and parse output
2015-10-06 22:09:07.2261|INFO|thread:21|NewCommitViewModel|Took 59ms to
load files for C:\Users\GAD\Documents\GitHub\-Place-script
2015-10-06 22:09:07.2261|INFO|thread:21|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 9:GitClient.cs:288 after blocking
0.0558862s
2015-10-06 22:09:07.4063|INFO|thread: 1|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 10:GitClient.cs:646
2015-10-06 22:09:07.4063|INFO|thread: 5|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 10:GitClient.cs:646 after waiting
2.1E-05s
2015-10-06 22:09:07.4063|INFO|thread:21|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 10:GitClient.cs:646 after blocking
0.0023358s
2015-10-06 22:09:07.7996|INFO|thread: 1|NewCommitViewModel|Took 573ms to
render file list for C:\Users\GAD\Documents\GitHub\-Place-script
2015-10-06 22:09:07.8016|INFO|thread: 1|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 11:RepositoryViewModel.cs:325
2015-10-06 22:09:07.8016|INFO|thread: 5|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 11:RepositoryViewModel.cs:325 after
waiting 3.67E-05s
2015-10-06 22:09:07.8016|INFO|thread: 5|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 11:RepositoryViewModel.cs:325 after
blocking 4.2E-06s
2015-10-06 22:09:07.8016|INFO|thread: 1|AsyncReaderWriterLock|Acquiring
concurrent scheduler for operation: 12:RepositoryViewModel.cs:325
2015-10-06 22:09:07.8016|INFO|thread: 5|AsyncReaderWriterLock|Acquired
concurrent scheduler for operation: 12:RepositoryViewModel.cs:325 after
waiting 1.48E-05s
2015-10-06 22:09:07.8016|WARN|thread:21|GetBranch`1|Could not resolve
branch origin/master
2015-10-06 22:09:07.8016|WARN|thread: 7|GetBranch`1|Could not resolve
branch origin/master
2015-10-06 22:09:07.8016|INFO|thread: 7|AsyncReaderWriterLock|Released
concurrent scheduler for operation: 12:RepositoryViewModel.cs:325 after
blocking 0.0042118s
2015-10-06 22:09:11.0815|INFO|thread: 1|RepositoryHost|Log in from cache
for login 'MALLOCkol' to host 'https://api.github.com/' SUCCEEDED
2015-10-06
22:09:11.0955|INFO|thread:26|ApplicationShellInitializer|Running post
login tasks. ~/.gitconfig is set up with user.name = 'MALLOCkol' and
user.email = 'filaret25@gmail.com'
2015-10-06 22:09:11.1076|INFO|thread:26|SSHKeyHelper|ssh-agent already
running
2015-10-06 22:09:11.1076|INFO|thread:26|PortablePackageManager|Already
extracted lfs-amd64.7z, returning 100%
2015-10-06 22:09:11.1146|INFO|thread:26|GitEnvironment|Process set up
with this SSH Agent info: 3648:/tmp/ssh-A1tKCBguHPpd/agent.3580
2015-10-06 22:09:11.1146|INFO|thread:26|GitEnvironment|PATH is
C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd;C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin;C:\Users\GAD\AppData\Local\Apps\2.0\Y1762BWD.M30\QYMZC3E1.2BQ\gith..tion_317444273a93ac29_0003.0000_30c6a4a3ecafb094;C:\Users\GAD\AppData\Local\GitHub\lfs-amd64_0.5.4;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\System32
2015-10-06 22:09:11.1146|INFO|thread:26|ProcessWrapper|Starting: Process
- FileName:
'C:\Users\GAD\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\ssh-add.exe',
Args: '"C:\Users\GAD\.ssh\github_rsa"', Working Directory:
C:\Users\GAD\AppData\Local\Temp\
2015-10-06 22:09:11.1436|INFO|thread: 4|SSHKeyHelper|Found existing SSH
key pair